### ISSUE TITLE
请问开发方式（文件结构）

### ISSUE THREAD

**Issue by xiejiachen** [dnc1994/Kaggle-Playground#1]
我看到您的文件夹里除了ipynb 还有.py文件

请问您是如何让它们一起工作的。

在其他IDE里调试好 再复制进jupyter运行吗？

**Comment by dnc1994** [comment]
其实是这样的，前期做预处理和研究 feature 主要在 ipynb 里做，因为方便随时修改和调试。
后面训练模型的那部分代码，在 ipynb 里面验证了没有 bug 以后，就保存成 .py 方便丢在一边跑。

**Comment by xiejiachen** [comment]
请问您用什么ide

**Comment by zxybazh** [comment]
直接用ipython notebook

**Comment by xiejiachen** [comment]
@zxybazh  感觉只用notebook,算法多起来了内存就装不下了

**Comment by xiejiachen** [comment]
@dnc1994  请问您的 .py 算法 读取文件是 从notebook里生成的存在内存里的变量读， 还是重新写一套 read_csv 再重新生成feature。

我在自己的roden上直接读 notebook里的变量名，显示错误。

**Comment by dnc1994** [comment]
@xiejiachen 我 ipynb 末尾有把 feature 导出到一个 csv，.py 就当然是直接读 csv。
“从 notebook 里生成的存在内存里的变量读” 这个应该做不到因为你每开一个 ipynb 都会启动一个新的 python kernel 连上去，它们之间应该是独立的……
而且我训练模型跟研究特征并不在一个机子上

**Comment by xiejiachen** [comment]
@dnc1994 十分感谢，收获良多。 您训练模型是用的什么ide呢请问

**Comment by dnc1994** [comment]
notebook 带来一些优势的同时的确对内存压力更大了
机子内存小的话只能多保存然后清理中间结果

**Comment by dnc1994** [comment]
一开始在 ipynb 里面写，后来复制到 .py 直接拿去跑了，不用 IDE。

**Comment by xiejiachen** [comment]
嗯， Thanks!
