### ISSUE TITLE
df_lev_dist_more_jaccard.csv问题

### ISSUE THREAD

**Issue by BoyuanJiang** [dnc1994/Kaggle-Playground#2]
看到Preprocess.ipynb中有这句代码append = pd.read_csv('df_lev_dist_more_jaccard.csv', encoding='ISO-8859-1')，运行中报错，请问df_lev_dist_more_jaccard.csv这个文件从哪来的？

**Comment by dnc1994** [comment]
这个我记得是在比赛的过程中有一段时间用了不太一样的方法算了一些距离，结果代码不小心删掉了，但是当时的dataframe导出成文件了还在，所以就直接导入也作为之后特征的一部分。你可以直接忽略，没什么重要性~

**Comment by BoyuanJiang** [comment]
ok，非常感谢您的回复
